### ISSUE TITLE
Missing LA in namespace DecGMCA

### ISSUE THREAD

**Issue by JulienNGirard** [CEA-jiangming/DecGMCA#3]
```
julien.girard@nancep1:~/git/DecGMCA/simu_CS_deconv$ python test_CS.py
Process of creating sources ......
5 approximate k-sparse sources of 4096samplings are created
Creation of sources finished.
Process of Creating mask ......
Random pixel selection (0.5 - 2048 pixels)
Creation of mask finished.
Traceback (most recent call last):
  File "test_CS.py", line 154, in <module>
    (S_est,A_est) = DecGMCA(V_N,MMat,n,Nx,Ny,Imax,epsilon[j],epsilonF,Ndim,wavelet=wavelet,scale=4,mask=mask,deconv=deconv,wname='starlet',thresStrtg=thresStrtg,FTPlane=FTPlane,fc=fc,logistic=logistic,postProc=postProc,postProcImax=postProcImax,Ksig=Ksig,positivityS=positivityS,positivityA=positivityA)
  File "../pyDecGMCA/boost_algoDecG.py", line 108, in DecGMCA
    Xe = SVTCompletion(V,MM,n,0.5,100)
  File "../pyDecGMCA/mathTools.py", line 375, in SVTCompletion
    U,s,V = LA.svd(Y,full_matrices=False)
```
Missing import or badly configured namespace

Patch in mathTools.py.
import numpy.linalg as LA

**Comment by CEA-jiangming** [comment]
Updated
